mgr:
  timezone: "UTC"
  date_fmt: "%m/%d/%y %H:%M"
  single_order:
    bidder_code: "hb"
    bidder_name: "Top Bid"
  test_run:
    line_item_limit: 2
  dry_run:
    id_prefix: 9999

googleads:
  version: 'v202011'
  line_items:
    micro_cent_factor: 1000000
    max_per_order: 450
    unlimited_end_datetime_types:
      - HOUSE
      - NETWORK
      - PRICE_PRIORITY
      - SPONSORSHIP

prebid:
  bidders:
    data: https://docs.prebid.org/dev-docs/bidder-data.csv
    key_char_limit: 20
    keys:
      - "hb_pb"
      - "hb_bidder"
      - "hb_adid"
      - "hb_size"
      - "hb_source"
      - "hb_format"
      - "hb_cache_host"
      - "hb_cache_id"
      - "hb_uuid"
      - "hb_cache_path"
      - "hb_deal"
    targeting_key: "hb_pb"
