line_item_manager:
  single_order:
    bidder_code: "hb"
    bidder_name: "Top Bid"

googleads:
  version: 'v202008'
  line_items:
    max_per_order: 450

prebid:
  bidders:
    data: https://docs.prebid.org/dev-docs/bidder-data.csv
    key_char_limit: 20
    keys:
      - "hb_pb"
      - "hb_bidder"
      - "hb_adid"
      - "hb_size"
      - "hb_source"
      - "hb_format"
      - "hb_cache_host"
      - "hb_cache_id"
      - "hb_uuid"
      - "hb_cache_path"
      - "hb_deal"
    targeting_key: "hb_pb"
